import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Example } from '@pmirau/lib--react-form'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <Example.InputOverview />
      <main className={styles.main}>
      </main>
    </div>
  )
}

export default Home
